project:
  type: website

website:
  title: "Journal"
  navbar:
    left:
      - text: My Data Journal
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: Scholarship
        href: scholarship.qmd
      
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



