project:
  type: website

website:
  title: "Portfolio"
  navbar:
    left:
      - text: Home
        href: index.qmd    
      - text: Projects
        href: projects.qmd
      - text: Scholarship
        href: scholarship.qmd
      - about.qmd
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



